{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
spec:
  ports:
    {{- range $serviceIndex, $service := .Values.service.app }}
    - port: {{ $service.port.servicePort }}
      name: "{{ $service.port.name }}"
      targetPort: {{ $service.port.targetPort }}
      protocol: {{ $service.port.protocol }}
    {{- end -}}
  selector:
    app: {{ template "name" . }}
  {{- end -}}